name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET SDK (ensure you're using the correct version for your project)
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0' # Adjust to the version you're using

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project (this checks for syntax errors and compilation issues)
    - name: Build
      run: dotnet build --configuration Release

    # Run tests (if you have tests)
    - name: Run tests
      run: dotnet test --no-build --configuration Release

    # Check code formatting (optional but recommended)
    - name: Check code formatting
      run: dotnet format --check --verbosity normal





