name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

   
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0' 


    - name: Restore dependencies
      run: dotnet restore CyberChatBot/CyberChatBot.sln

    - name: Build
      run: dotnet build CyberChatBot/CyberChatBot.sln --configuration Release

    - name: Run tests
      run: dotnet test CyberChatBot/CyberChatBot.sln --no-build --configuration Release

    - name: Check code formatting
      run: dotnet format --check --verbosity normal CyberChatBot/CyberChatBot.sln






