name: CI Build and Format Check


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: CyberChatBot/CyberChatBot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore CyberChatBot.csproj

    - name: Build the project
      run: dotnet build CyberChatBot.csproj --no-restore

    - name: Check code formatting
      run: dotnet format CyberChatBot.csproj --verify-no-changes




