name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./CyberChatBot 

    - name: Build the project
      run: dotnet build --configuration Release
      working-directory: ./CyberChatBot  

    - name: Run tests
      run: dotnet test --configuration Release
      working-directory: ./CyberChatBot  

    - name: Check code formatting
      run: dotnet format --check
      working-directory: ./CyberChatBot/CyberChatBot 
